<?php
session_start();
require_once 'includes/audit_logger.php'; // ensure this is here just in case

// Database configuration
$db_host = "localhost";
$db_user = "root";
$db_pass = "";
$db_name = "bookwagon_db";

$conn = new mysqli($db_host, $db_user, $db_pass, $db_name);
if ($conn->connect_error) {
    die("System error: Unable to connect to the database.");
}
require_once 'includes/GoogleAuthenticator.php';
require_once 'includes/audit_logger.php';

// Check if user is in the middle of 2FA setup
if (!isset($_SESSION['pending_2fa_setup']) || !isset($_SESSION['temp_user_id'])) {
    header('Location: login.php');
    exit;
}

$ga = new GoogleAuthenticator();
$error = '';

// Generate a new secret if we don't have one in this session yet
if (!isset($_SESSION['temp_2fa_secret'])) {
    try {
        $_SESSION['temp_2fa_secret'] = $ga->createSecret();
    } catch (Exception $e) {
        $error = "Failed to generate security token.";
    }
}

$secret = $_SESSION['temp_2fa_secret'];
$email = $_SESSION['temp_email'];
// Generate the QR Code URL to display
$qrCodeUrl = $ga->getQRCodeGoogleUrl('BookWagon', $secret, $email);

if ($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['verify_code'])) {
    $code = trim($_POST['code']);
    
    // Verify the code
    $checkResult = $ga->verifyCode($secret, $code, 2); // 2 = 2*30sec clock tolerance
    
    if ($checkResult) {
        // Success! Save the secret to the database and increment login count
        $stmt = $conn->prepare("UPDATE users SET google2fa_secret = ?, is_2fa_enabled = 1, login_count = login_count + 1 WHERE id = ?");
        $stmt->bind_param("si", $secret, $_SESSION['temp_user_id']);
        
        if ($stmt->execute()) {
            // Setup complete. Log them in fully.
            $_SESSION['loggedin'] = true;
            $_SESSION['user_id'] = $_SESSION['temp_user_id'];
            $_SESSION['email'] = $_SESSION['temp_email'];
            $_SESSION['user'] = $_SESSION['temp_email'];
            $_SESSION['firstname'] = $_SESSION['temp_firstname'];
            $_SESSION['lastname'] = $_SESSION['temp_lastname'];
            $_SESSION['usertype'] = $_SESSION['temp_usertype'] ?? 'user';
            $_SESSION['login_count'] = 1;
            
            // Clean up temp vars
            unset($_SESSION['pending_2fa_setup']);
            unset($_SESSION['temp_user_id']);
            unset($_SESSION['temp_email']);
            unset($_SESSION['temp_firstname']);
            unset($_SESSION['temp_lastname']);
            unset($_SESSION['temp_usertype']);
            unset($_SESSION['temp_login_count']);
            unset($_SESSION['temp_2fa_secret']);
            
            log_activity($_SESSION['user_id'], '2FA Setup', 'User successfully setup 2FA.');
            
            // First time login always goes to welcome page
            header('Location: welcome.php');
            exit;
        } else {
            $error = "Database error. Please try again.";
        }
    } else {
        $error = "Invalid verification code. Please try again.";
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Set Up Two-Factor Authentication</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body { background-color: #f8f9fa; }
        .setup-container { max-width: 500px; margin: 50px auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); text-align: center; }
        .qr-code { margin: 20px 0; border: 1px solid #ddd; padding: 10px; border-radius: 8px; }
        .secret-key { font-family: monospace; font-size: 1.2em; letter-spacing: 2px; background: #eee; padding: 10px; display: inline-block; margin-top: 10px; border-radius: 4px; }
    </style>
</head>
<body>
    <div class="setup-container">
        <h2>Secure Your Account</h2>
        <p class="text-muted">Set up Two-Factor Authentication (2FA) using Google Authenticator or Authy.</p>
        
        <?php if (!empty($error)): ?>
            <div class="alert alert-danger"><?php echo htmlspecialchars($error); ?></div>
        <?php endif; ?>
        
        <div class="step">
            <h5>1. Scan this QR Code</h5>
            <img src="<?php echo htmlspecialchars($qrCodeUrl); ?>" alt="QR Code" class="qr-code">
            <p>Or manually enter this key in your app:</p>
            <div class="secret-key"><?php echo htmlspecialchars($secret); ?></div>
        </div>
        
        <hr>
        
        <div class="step mt-4">
            <h5>2. Verify Setup</h5>
            <p>Enter the 6-digit code generated by your app to complete setup.</p>
            <form action="setup_2fa.php" method="POST">
                <div class="mb-3">
                    <input type="text" name="code" class="form-control form-control-lg text-center" placeholder="123456" maxlength="6" required autocomplete="off">
                </div>
                <button type="submit" name="verify_code" class="btn btn-primary btn-lg w-100">Verify and Enable 2FA</button>
            </form>
        </div>
    </div>
</body>
</html>
